modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/frank89722/Staaaaaaaaaaaack/issues" #optional
[[mods]] #mandatory
# The modid of the mod
modId="staaaaaaaaaaaack"
version="${file.jarVersion}"
displayName="Staaaaaaaaaaaack"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://modrinth.com/mod/staaaaaaaaaaaack"
logoFile="logo.png"
authors="frankV"
description='''
Drops are merged!
'''
[[dependencies.staaaaaaaaaaaack]]
   modId="neoforge"
   type="required"
   versionRange="[21.5,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.staaaaaaaaaaaack]]
   modId="minecraft"
   type="required"
   versionRange="[1.21.5,1.22)"
   ordering="NONE"
   side="BOTH"

[[mixins]]
   config="staaaaaaaaaaaack.mixins.json"